In [1]:
import numpy
import math
from matplotlib import pyplot
%matplotlib inline




g = 9.8 
Po = 1.091
r = 0.5
A = r**2*math.pi
Ve = 325
Cd = 0.15
Mp0 = 100 
Vm = 20
h0 = 0
Ms = 50
v0 = 0


In [2]:
def f(u):
    h = u[0]
    v = u[1]
    Mp = u[2]
    return numpy.array([v, -g+(Vm*Ve)/(Mp+Ms)-Po*v*A*Cd*math.fabs(v)/(2*(Mp+Ms)),-Vm])




def f2(u):
    h = u[0]
    v = u[1]
    Mp = u[2]
    return numpy.array([v, -g-Po*v*A*Cd*math.fabs(v)/(2*Ms), 0])

In [3]:
def euler_step(u, f, dt):
    """Returns the solution at the next time-step using Euler's method.
    
    Parameters
    ----------
    u : array of float
        solution at the previous time-step.
    f : function
        function to compute the right hand-side of the system of equation.
    dt : float
        time-increment.
    
    Returns
    -------
    u_n_plus_1 : array of float
        approximate solution at the next time step.
    """
    
    return u + dt * f(u)


In [23]:
T = 40                          # final time
dt = 0.1                           # time increment
N = int(T/dt) + 1                  # number of time-steps
t = numpy.linspace(0, T, N)      # time discretization

# initialize the array containing the solution for each time-step
u = numpy.empty((N, 3))
u[0] = numpy.array([h0, v0, Mp0])# fill 1st element with initial values

# time loop - Euler method
for n in range(N-1):
    if t[n] < 5:
        u[n+1] = euler_step(u[n], f, dt)
    elif ((t[n] >= 5) & (u[n, 0] > 0)):
        u[n+1] = euler_step(u[n], f2, dt)
    elif u[n, 0] < 0:
        break
print(n)   
        
print(t)

371
[  0.    0.1   0.2   0.3   0.4   0.5   0.6   0.7   0.8   0.9   1.    1.1
   1.2   1.3   1.4   1.5   1.6   1.7   1.8   1.9   2.    2.1   2.2   2.3
   2.4   2.5   2.6   2.7   2.8   2.9   3.    3.1   3.2   3.3   3.4   3.5
   3.6   3.7   3.8   3.9   4.    4.1   4.2   4.3   4.4   4.5   4.6   4.7
   4.8   4.9   5.    5.1   5.2   5.3   5.4   5.5   5.6   5.7   5.8   5.9
   6.    6.1   6.2   6.3   6.4   6.5   6.6   6.7   6.8   6.9   7.    7.1
   7.2   7.3   7.4   7.5   7.6   7.7   7.8   7.9   8.    8.1   8.2   8.3
   8.4   8.5   8.6   8.7   8.8   8.9   9.    9.1   9.2   9.3   9.4   9.5
   9.6   9.7   9.8   9.9  10.   10.1  10.2  10.3  10.4  10.5  10.6  10.7
  10.8  10.9  11.   11.1  11.2  11.3  11.4  11.5  11.6  11.7  11.8  11.9
  12.   12.1  12.2  12.3  12.4  12.5  12.6  12.7  12.8  12.9  13.   13.1
  13.2  13.3  13.4  13.5  13.6  13.7  13.8  13.9  14.   14.1  14.2  14.3
  14.4  14.5  14.6  14.7  14.8  14.9  15.   15.1  15.2  15.3  15.4  15.5
  15.6  15.7  15.8  15.9  16.   16.1  16.2  16.

In [16]:
print(u)


[[  0.00000000e+00   0.00000000e+00   1.00000000e+02]
 [  0.00000000e+00   3.35333333e+00   9.80000000e+01]
 [  3.35333333e-01   6.76473695e+00   9.60000000e+01]
 [  1.01180703e+00   1.02347774e+01   9.40000000e+01]
 [  2.03528477e+00   1.37639914e+01   9.20000000e+01]
 [  3.41168392e+00   1.73528824e+01   9.00000000e+01]
 [  5.14697215e+00   2.10019169e+01   8.80000000e+01]
 [  7.24716384e+00   2.47115211e+01   8.60000000e+01]
 [  9.71831596e+00   2.84820769e+01   8.40000000e+01]
 [  1.25665236e+01   3.23139174e+01   8.20000000e+01]
 [  1.57979154e+01   3.62073226e+01   8.00000000e+01]
 [  1.94186476e+01   4.01625151e+01   7.80000000e+01]
 [  2.34348992e+01   4.41796545e+01   7.60000000e+01]
 [  2.78528646e+01   4.82588327e+01   7.40000000e+01]
 [  3.26787479e+01   5.24000680e+01   7.20000000e+01]
 [  3.79187547e+01   5.66032998e+01   7.00000000e+01]
 [  4.35790847e+01   6.08683819e+01   6.80000000e+01]
 [  4.96659229e+01   6.51950768e+01   6.60000000e+01]
 [  5.61854305e+01   6.95830

In [24]:
print(u[371, 1])


-85.9573865732


In [48]:
print(u[ , 0])


SyntaxError: invalid syntax (<ipython-input-48-1bc7ad182eae>, line 1)